config/routes.rb
Aml::Application.routes.draw do

  match 'communities/' => 'communities#index'
  resources :photos, only: [:show, :index]
  match 'about/' => 'about#index'
  match 'lures/' => 'lures#index'

  root :to => 'home#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  protect_from_forgery
  layout 'application'

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/communities_controller.rb
class CommunitiesController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def index
  end

end

app/controllers/lures_controller.rb
class LuresController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ActionController::Base
  protect_from_forgery
  layout 'home'

  def show
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.slim
div.kpanel.kcenter

  div#container style="width:385px;height:300px;float:right;margin:10px;left:65px;"
    div#home-slider
      div#slides-tom
        div.slides_container
          a
            =image_tag("photos/tom_1.png")
          a
            =image_tag("photos/tom_2.png")
          a
            =image_tag("photos/tom_3.png")

  div style="text-align:justify"
    h1 UNCLE TOM

    p.customfont He's the reason we make these lures.  His love and passion for fishing bordered on fanaticism.
                 He'd fish any time, any weather, any place.
                 And he was good.  The best.  He'd be shoulder to should with you, fishing in the exact same spot, and he'd get the fish every time.
                 He was so willing to teach anyone his skills, and we all listened with open ears.
                 Unfortunately Tom passed away a few years ago, and is GREATLY missed.
                 But he did pass on his abilities (well most of them) and for sure his love and passion, to a few of his family and friends.
                 To honor Tom, and to continue with his and now our passion and love, we make these lures.

    h2 Hey Tom, remember:

    div style="margin-left: 40px"
      ul
        li
          p.customfont Fishing in Colorado and getting a lure caught in your nostril?
                       Not being able to take it out, and on the way to the hospital decided to stop in the bar for a drink first!

      ul
        li
          p.customfont Once, he got the name of a good muskie fisherman in Meadville, PA.
                       He immediately jumped in his car and drove, and upon getting there he realized all he had was a name.
                       He grabbed a phonebook in the nearest phone booth, found the name, and got the address and knocked on his front door (at 3AM).
                       A woman answered the door, invited him in, and her, her husband, and Tom talked till daylight about muskie fishing in French Creek.

      ul
        li
          p.customfont Your two otter "friends".

  p.customfont Tom's passion and love for fishing was incomprehensable to most.
               We want to use the passion he had and passed on to us to create fishing lures that would make Tom proud.

  p.customfont I can see him now, shoulder to shoulder wth us, using one of our lures which we hand crafted, tested, modified, redesigned over and over....
               and he'd be the one catching the fish.  We miss you and love you Tom, so much.

app/views/communities/index.html.slim
/div.kpanel.kcenter
/  table border=1 width="100%"
/    tr
/      td
/        = render partial: "/shared/twitter"
/      td
/        = render partial: "/shared/facebook_like"
/      td
/        p Youtube videos

div style="width:900px;margin:0 auto;"
  table style="width:100%"
    tr
      td width="33%"
        div.kpanel
          = render partial: "/shared/twitter"

      td width="33%"
        div.kpanel
          = render partial: "/shared/facebook_like"

      td width="33%"
        div.kpanel
          p YouTube Videos 490px high

    tr
      td colspan="3"
        div.kpanel
          center
            table
              tr
                td
                  p Contact the Angry Monkey directly:
                td
                  =link_to("angrymonkeylures@gmail.com", "mailto:angrymonkeylures@gmail.com")

app/views/home/index.html.slim
div.content
  div#container
    div#home-slider
      div#slides-home
        div.slides_container
          a href="/lures"
            =image_tag("slider/slide-1.jpg")
          a href="https://www.facebook.com/pages/Angry-Monkey-Fishing-Lures/140672516118134" target="_blank"
            =image_tag("slider/slide-2.png")
          a href="#"
            =image_tag("slider/slide-3.png")
        a.prev href="#"
          =image_tag("slider/arrow-prev.png")
        a.next
          =image_tag("slider/arrow-next.png")
      =image_tag("slider/frame-black.png", id: "frame")

  div

    div style="width:930px;margin:0 auto;"
      div.kpanel
        center
          h1 The Angry Monkey makes premium cedar fishing lures for fresh waters.
          table
            tr
              td valign="top"
                =image_tag("monkey_head.png", size: "96x96")
              td
                p.customfont.triangle-border.left "To catch a mean fish, you need a mean lure."

        table width="100%" cellpadding="10"
          tr
            td width="37%" align="center" valign="top"

              h2 See Our Lures

              =link_to(image_tag("lures/DSC_1378.png", width: "200px"), lures_path)
              =link_to(image_tag("lures/DSC_1376.png", width: "200px"), lures_path)

            td width="26%" align="center" valign="top"

              h2 About Us

              =link_to(image_tag("photos/tom_1.png", size: "128x128"), about_path)

            td width="37%" align="center" valign="top"

              h2 Connect With The Monkey

              table
                tr
                  td align="center" valign="top"
                    =link_to(image_tag("icons/facebook_logo.png"), "https://www.facebook.com/pages/Angry-Monkey-Fishing-Lures/140672516118134")
                  td align="center" valign="top"
                    =link_to(image_tag("icons/twitter_logo.png"), "https://twitter.com/AngryMonkeyLure")
                tr
                  td align="center" valign="top"
                    =image_tag("icons/youtube_logo.jpg")
                  td align="center" valign="top"
                    =link_to(image_tag("icons/gmail_logo.jpg"), "mailto:angrymonkeylures@gmail.com")

app/views/layouts/application.html.slim
doctype html
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  = favicon_link_tag 'favicon.ico'
 
  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "Angry Monkey Lures"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

body.body

  = render partial: "shared/facebook_script.html"

  div.wrapper
    div.home-header
      =link_to(image_tag("logo_aml_long.png", style: "height: 235px"), root_path)

      / div.main-nav
      /   ul
      /     li =link_to("About", "/about")

    == yield

  = javascript_include_tag "application"

footer.footer
  p &copy; Copyright 2013 Angry Monkey Fishing Lures LLC.

app/views/lures/index-orig.html.slim
div.kpanel.kcenter

  p This page is currently being designed.  But here are a few right now!  Check back soon to see the standard lure colors.

  div.kcenter

    table cellpadding="20"
      tr
        td
          h2 Fat Back (6" and 8")
          =image_tag("lures/fb1-chub.png", width: "300px")
          br
          p
            | Fat Back is a crank bait. Hooks are size 1.
          p
            | The front of the lure moves side to side.  The bulbous back end moves side to side as well as rolls. You can change the depth of the lure by manipulating the angle of the bill - the higher the bill the deeper it will run, the lower the bill the shallower it will run. Depth between 1ft to 14ft.
          p See it in action on the video (soon!)

      tr
        td valign="top"
          h2 Tom's Dislocated Minnow (7.5" and 8.5")
          =image_tag("lures/tdm1-bone.png", width: "300px")
          =image_tag("lures/tdm2-green_sunfish.png", width: "300px")
          br
          p
            | Tom’s Dislocated Minnow is a crank bait. Hooks are size 1/0 and 2/0.
          p
            | The front of the lure aggresively moves side to side and rolls. The rear of the lure moves violently side to side. It's mean!  The faster it is retrieved the move aggressive the movement of the lure.  Depth depends on the angle of the bill. The higher the bill the deeper it will run. If the bill is bent downward the shallower it will run. Depth between 1ft to 14ft.
          p See it in action on the video (soon!)

app/views/lures/index.html.slim
div.kpanel.kcenter

  div.kcenter

    table cellpadding="20"
      tr
        td
          h2 Fat Back 6"
          =image_tag("lures/fb1-chub.png", width: "300px")
          br
          p
            | Fat Back is a crank bait. Hooks are size 1. Split rings are size 3 heavy.
          p
            | The front of the lure moves side to side.  The bulbous back end moves side to side as well as rolls. You can change the depth of the lure by manipulating the angle on the bill - the higher the bill the deeper it will run the lower the bill the shallower it will run. Depth between 1ft to 14ft.
          p See it in action on the video (soon!)

      tr
        td valign="top"
          h2 Tom's Dislocated Minnow (7.5" and 8.5")
          =image_tag("lures/tdm1-bone.png", width: "300px")
          =image_tag("lures/tdm2-green_sunfish.png", width: "300px")
          br
          p
            | Tom’s Dislocated Minnow is a crank bait. Hooks are size 1/0 and 2/0.
          p
            | The front of the lure aggresively moves side to side and rolls. The rear of the lure moves violently side to side. It's mean!  The faster it is retrieved the move aggressive the movement of the lure.  Depth depends on the angle of the bill. The higher the bill the deeper it will run. If the bill is bent downward the shallower it will run. Depth between 1ft to 14ft.
          p See it in action on the video (soon!)

  div.kpanel
    p
      | Interested in purchasing some of these bad boys now?  Simply email me at 
      =link_to("angrymonkeylures@gmail.com ", "mailto:angrymonkeylures@gmail.com")
      | until i make online purchasing available.  Refer to the pricing chart below.

    br

    table class="ktable"
      tr
        th Lure
        th Price (US $)
      tr
        td Fat Back
        td $15.99
      tr
        td Tom's Dislocated Minnow 7.5"
        td $17.99
      tr
        td Tom's Dislocated Minnow 8.5"
        td $19.99

    br
    p Taxes are not included in the price of the lure.
      Standard UPS or USPS Ground rates apply.

app/views/photos/index.html.slim
div.row
  div.small-12.columns
    | Put in Clearing image view....

    ul.clearing-thumbs data-clearing=""
      li
        a.th href="photos/img1.jpg"
          =image_tag "photos/img1.jpg"
      li
        a.th href="photos/img2.jpg"
          =image_tag "photos/img2.jpg"
      li
        a.th href="photos/img3.jpg"
          =image_tag "photos/img2.jpg"